language: java

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

script:
  - ./gradlew check installDist &&
    cp docker/Dockerfile georocket-server/build/install/Dockerfile &&
    docker build -t georocket/georocket georocket-server/build/install &&
    cd georocket-server/integration-tests &&
    ./test.sh &&
    cd ../.. &&
    if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker push georocket/georocket;
    fi

cache:
  directories:
    - $HOME/.gradle
