integration-tester:
  build: .
  links:
    - georocket_standalone
    - georocket_mongo
    - georocket_s3
    - georocket_hdfs
    - mongo
    - s3
    - hdfs

# GeoRocket instances
georocket_standalone:
  image: georocket/georocket

georocket_mongo:
  image: georocket/georocket
  volumes:
    - ./conf/georocket_mongo:/usr/local/georocket-server/conf
  links:
    - mongo

georocket_s3:
  image: georocket/georocket
  volumes:
    - ./conf/georocket_s3:/usr/local/georocket-server/conf
  links:
    - s3

georocket_hdfs:
  image: georocket/georocket
  volumes:
    - ./conf/georocket_hdfs:/usr/local/georocket-server/conf
  links:
    - hdfs

# Back-ends
mongo:
  image: mongo

s3:
  image: scality/s3server
  # Allow s3 server to be accessed through the "s3" domain name.
  # If we don't add the domain name to the config file the server will
  # fail with an authentication error.
  command: bash -c "sed -i s/\\\"localregion\\\".*$$/\\\\0,\\\\n\\\\t\\\"specifiedregion\\\":\ [\\\"s3\\\"]/ /usr/src/app/config.json && npm start"

hdfs:
  image: sequenceiq/hadoop-docker:2.7.1
