integration-tester:
  build: .
  command: hdfs
  links:
    - georocket_hdfs
    - hdfs

georocket_hdfs:
  image: georocket/georocket
  volumes:
    - ./conf/georocket_hdfs:/usr/local/georocket-server/conf
  links:
    - hdfs

hdfs:
  image: georocket/hadoop-docker:2.7.3
